name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install FTP-Deploy Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ENV.FTP_HOST }}
          username: ${{ secrets.ENV.FTP_USERNAME }}
          password: ${{ secrets.ENV.FTP_PASSWORD }}
          local-dir: ./dist
          server-dir: ${{ secrets.ENV.FTP_PATH }}
          exclude: |
            .git*
            .github/
            README.md
